name: 'My Composite Action'
description: 'Runs a custom build and test sequence'
inputs:
  build-path:
    required: true
    description: 'Path to build'

runs:
  using: 'composite'
  steps:
    - name: Print build path
      run: echo "Build path is ${{ inputs.build-path }}"
      shell: bash
