name: Upload Single Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the project
        run: echo "Building project..."

      - name: Upload build artifact
        uses:  actions/upload-artifact@v3.1.2
        with:
          name: build-output
          path: ./dist/*
