name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Project
        run: echo "Building project..." > build.txt
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2

        with:
          name: build-artifact
          path: build.txt

  test:
    runs-on: ubuntu-latest
    needs: build  # Waits for the build job to complete
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3.1.2  # Use exact version
        with:
          name: build-artifact  # Must match the uploaded artifact name
          path: ./downloads  # Optional, defaults to the root directory
        
      - name: Verify Artifact
        run: cat ./downloads/build.txt



