name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Build Project
        run: |
          echo "Building project..."
          echo "This is my build output" > build.txt
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@main


        with:
          name: build-artifact
          path: build.txt



