# File: .github/workflows/caller.yml
name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable1.yml
    with:
      environment: production

