name: Call Reusable Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable1.yml
    with:
      environment: production
