name: Download Artifacts

on:
  workflow_run:
    workflows: ["Build and Upload Artifacts"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-build  # Must match the upload name
          path: ./downloads
        
      - name: Verify Artifact
        run: cat ./downloads/build.txt

