name: Download Artifacts

on:
  workflow_run:
    workflows: ["Build and Upload Artifacts"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Download Build Artifact
        uses: actions/download-artifact@v3.1.2
        with:
          name: my-build
          path: ./downloads
        
      - name: Verify Artifact
        run: cat ./downloads/build.txt




