name: Job Outputs Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.set-name.outputs.name }}

    steps:
      - name: Set artifact name
        id: set-name
        run: echo "name=my-artifact" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Use artifact name from build
        run: echo "Deploying artifact:${{ needs.build.outputs.artifact-name }}"










