name: Run Docker Action

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Custom Docker Action
        uses: ./.github/actions/my-docker-action
        with:
          name: "Swati"

