name: Run Custom Action

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Greet Action
        uses: ./.github/actions/my-custom-action
        with:
          name: 'Swati'

