name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Application
        run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Runs only if 'build' job succeeds
    steps:
      - name: Deploy to Production
        run: echo "Deploying..."
