name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Environment:${{ inputs.environment }}"


