name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00 UTC

jobs:
  security-check:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Use latest checkout action

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript  # Change according to your project

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
