# .github/workflows/steps-example.yml

name: Steps Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4

      - name: Step 2 - Print Hello
        run: echo "Hello from Step 2 👋"

      - name: Step 3 - List files in repo
        run: ls -al

      - name: Step 4 - Create a file
        run: echo "This is a sample file" > example.txt

      - name: Step 5 - Show contents of the file
        run: cat example.txt
